development of GWAS data - Manhattan plots
intermine/bluegenes-gwas-visualizer pull request #1
Opened 2020-07-23 23:32 UTC by Sakshisrivastava413

Created GWAS Manhattan plots where genomic coordinates are displayed along the X-axis, with the negative logarithm of the association P-value for each SNP displayed on the Y-axis, meaning that each dot on the Manhattan plot signifies a SNP.
Support both humanmine and flymine.

2020-08-11 15:08 UTC, heralden requested changes
The code works and looks great! I see there has been some miscommunication about whether it should support genes or GWAS IDs, but the code is still correct, so we only have to change the specification. :smile_cat: Please see my comments.

> Support both humanmine and flymine.

I think you mean Soymine instead of Flymine, right?

2020-08-11 15:08 UTC, heralden commented on config.json
> +    ["Gene"]
This should be
```
  "accepts": ["id", "ids"],
  "classes": ["GWAS"],
```
so it will show on both GWAS result pages, and on a results page containing one or more GWAS.

2020-08-11 15:08 UTC, heralden commented on demo.html
> +          }
To work with the changes I suggested in `config.json`, "Gene" needs to be changed to "GWAS".

Also, would probably be a good idea to update the *flymine* comment to *soymine*, as Flymine doesn't have GWAS.

2020-08-11 15:08 UTC, heralden commented on src/index.js
> +			entity={imEntity.Gene}
This `.Gene` should also be changed to `.GWAS`

2020-08-11 15:08 UTC, uosl commented on src/query.js
> +			values: geneId
Sorry, I probably explained myself poorly during the call!

We will drop the idea of matching genes, so this constraint should be identical to the Soymine query:
```
	where: [
		{
			path: 'id',
			op: 'ONE OF',
			values: geneId
		}
	]
```

2020-08-11 15:08 UTC, uosl commented on src/ScatterPlot.js
> +				display: 'flex',
There is a lot of inline style here that doesn't seem to change dynamically. Can we assign them to CSS classes in `style.less` instead?

2020-08-12 07:39 UTC, Sakshisrivastava413 commented
> I think you mean Soymine instead of Flymine

Yea, That was a typo. :P 
Worked on suggestions. Please have a look.

2020-08-12 10:46 UTC, heralden approved these changes
Thanks! Everything seems correct now.

Just so you know, I will hold off on creating an issue for supporting the SNP report page. I'm not sure if it would be very useful as a bar chart, compared to the im-table already showing this info.

2020-08-12 10:46 UTC, merged